name: Node.js CI

# Run on every push or pull request to the 'main' branch (you can change this to your preference)
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.9.0]  # You can adjust the Node.js version according to your project

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # Install dependencies using Makefile
      - name: Install dependencies
        run: make install-deps

      # Step to run both linter and tests using Makefile
      - name: Run linter and tests
        run: make run-checks
