name: Run linter and tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-checks:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.9.0]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: make install-deps

      - name: Run linter and tests
        run: make run-checks

  build-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build image
        run: make build-image
